### YamlMime:UniversalReference
items:
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode:enum'
    summary: |-
      カスタム関数のエラーコード。 関数を呼び出したセルにエラーコードが表示されます。

      これらのエラーコードに加えて、カスタムエラーメッセージが表示されます。 カスタムメッセージはエラーインジケーターメニューに表示されます。このメニューには、エラーが発生した各セルのエラーフラグの上にマウスカーソルを置くことでアクセスします。
    name: CustomFunctions.ErrorCode
    fullName: CustomFunctions.ErrorCode
    langs:
      - typeScript
    type: enum
    package: custom-functions-runtime!
    children:
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
    summary: 'このエラーコードは、使用される関数が0または空のセルで除算されていることを示します。 JavaScript では0で除算が可能なので、この条件を検出するにはエラーハンドラーを慎重に記述する必要があることに注意してください。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: divisionByZero
    fullName: divisionByZero
    langs:
      - typeScript
    type: field
    numericValue: '"#DIV/0!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
    summary: 'このエラーコードは、関数名に入力ミスがあることを示しています。 このエラーコードは、カスタム関数の入力エラーとしてサポートされていますが、カスタム関数の出力エラーとしてはサポートされていないことに注意してください。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidName
    fullName: invalidName
    langs:
      - typeScript
    type: field
    numericValue: '"#NAME?"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
    summary: 'このエラーコードは、関数内の数値に問題があることを示しています。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidNumber
    fullName: invalidNumber
    langs:
      - typeScript
    type: field
    numericValue: '"#NUM!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
    summary: 'このエラーコードは、関数が無効なセルを参照していることを示します。 このエラーコードは、カスタム関数の入力エラーとしてサポートされていますが、カスタム関数の出力エラーとしてはサポートされていないことに注意してください。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidReference
    fullName: invalidReference
    langs:
      - typeScript
    type: field
    numericValue: '"#REF!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
    summary: 'このエラーコードは、関数の値が正しくないデータ型であることを示します。 必要に応じて、エラーコードに加えてカスタムエラーメッセージを使用することもできます。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: invalidValue
    fullName: invalidValue
    langs:
      - typeScript
    type: field
    numericValue: '"#VALUE!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
    summary: 'このエラーコードは、関数またはサービスを使用できないことを示します。 必要に応じて、エラーコードに加えてカスタムエラーメッセージを使用することもできます。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: notAvailable
    fullName: notAvailable
    langs:
      - typeScript
    type: field
    numericValue: '"#N/A"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
    summary: 'このエラーコードは、関数内の範囲が交差していないことを示します。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
    name: nullReference
    fullName: nullReference
    langs:
      - typeScript
    type: field
    numericValue: '"#NULL!"'