### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  カスタム関数のエラーコード。 関数を呼び出したセルにエラーコードが表示されます。


  これらのエラーコードに加えて、カスタムエラーメッセージが表示されます。 カスタムメッセージはエラーインジケーターメニューに表示されます。このメニューには、エラーが発生した各セルのエラーフラグの上にマウスカーソルを置くことでアクセスします。
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、使用される関数が0または空のセルで除算されていることを示します。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数名に入力ミスがあることを示しています。 このエラーコードは、カスタム関数の入力エラーとしてサポートされていますが、カスタム関数の出力エラーとしてはサポートされていないことに注意してください。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数内の数値に問題があることを示しています。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数が無効なセルを参照していることを示します。 このエラーコードは、カスタム関数の入力エラーとしてサポートされていますが、カスタム関数の出力エラーとしてはサポートされていないことに注意してください。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数の値が正しくないデータ型であることを示します。 必要に応じて、エラーコードに加えてカスタムエラーメッセージを使用することもできます。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数またはサービスを使用できないことを示します。 必要に応じて、エラーコードに加えてカスタムエラーメッセージを使用することもできます。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'このエラーコードは、関数内の範囲が交差していないことを示します。 カスタムエラーメッセージを使用することはできません。 \[[API set: Customfindwindow runtime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: cec80f674bc573e3e3d3679ab96792ea5e469ce3
  ms.sourcegitcommit: a6ecbc9abca2ab5c82af4c869e3e2d72c999a4c1
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 12/02/2020
  ms.locfileid: "49538403"
